spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/smartspirit
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=k8pQ2xM9vL4nR7tY1wZ5cB3dF6gH0jK2mN4qS8vX1zA3bE7dG9hJ2lP5rT8wY0u
jwt.expiration.ms=180000
jwt.refresh.expiration.ms=604800000

server.port=8080